on:
  # Trigger the workflow on push or
  # pull request, but only for the
  # master branch.
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # Weekly run to account for
  # changed dependencies.
  schedule:
    - cron: '17 04 * * 0'

name: CI
jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        compiler: ['gcc', 'clang']
      fail-fast: false
    env:
      CC: ${{ matrix.compiler }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the code
        run: make

      - name: Test creating the release archive
        run: make distcheck
